# 03. Making the most of a Jupyter Notebook

### Objectives

+ Know where Jupyter Notebooks excel and where they fail
+ Know the most common keyboard shortcuts
+ Use the five step process when doing a data exploration
+ Limit the amount of code you write in a single cell
+ Continuously verify that each line of code is working as you would expect
+ Use **alt + enter** to execute cells at the end of the notebook

## Minimal sufficiency at Jupyter Notebooks
To get the most out of this course, you need to have a minimum level of sufficiency with the Jupyter Notebooks programming environment. All programming environments have tools and commands that will provide for a much better and efficient experience. Even something as simple as your email client has many tools available to you to ease the process of composing an email. 

## No programming environment is best for all situations for every single person
One of the first things you need to be aware of is that the Jupyter Notebook has limitations just like any tool. It is not the best tool for every situation. There are certain situations that Jupyter Notebooks excel at and there are others where it fails. Depending on what you are doing, Jupyter may or may not be the appropriate tool.

## Where Jupyter Notebooks Excel
Jupyter Notebooks are excellent for constructing data explorations that incorporate code, visualizations, text, images, videos, and math text. Essentially, they are great at building a report that someone can read and get information from. They are great for blog posts, teaching, formal reports, and interview assignments.

These notebooks are pretty good at prototyping solutions or writing short snippets of code. There are also many projects and additional tools that have been built to support the notebooks.

### Iterative and interactive workflow
One of the best features of the notebook is that you can run one line of code, get output, and then use this output to run the next line of code. For many scientists, it will be absolutely necessary to process their thinking one line at a time. Writing multiple lines of code in a row just doesn't make sense because there needs to be some analysis or decision on the output of the previous line before continuing.

This type of workflow is **iterative**, because we are constantly running code, looking at output, modifying it and then repeating this process. It is **interactive** because we are getting results immediately upon running the code.

### Google Colaboratory
One of the most popular supporters of Jupter Notebooks is Google. They have built a product called Google Colaboratory where you can make Juptyer Notebooks in the cloud all for free. This makes them easy to collaborate on with others. You can actually open up any Jupyter Notebook stored in a public GitHub repository on Google Colaboratory.

### Opening up a public GitHub Jupyter Notebook on Google Colaboratory
Navigate to the [Google Colaboratory][1] home page. You should see an orange pop-up window. Click on the **GitHub** tab and type in **dunerdata** in the top line and press enter. You should see a list of all the public notebooks for the DunderData organization. Open up one of the notebooks now.

### Using Jupyter as a light-weight Interactive Dashboard
There are a number of [interactive widgets][2] that you can embed into the Notebook to give a user control. There are also interactive visualization libraries such as [bokeh][3] and [plotly][4] that both provide powerful tools for dashboards.
 
## Where Jupyter Notebooks Fail
You might not like notebooks. Don't fear, you will not be alone. There is no mandatory requirement to use Jupyter Notebooks to do data science. Traditional software development, such as building an application, would not be a time where Jupyter Notebooks would be a good choice. Other programming environments, such as PyCharm or Visual Studio Code, provide much better tools to organize, test, write, refactor, debug and version control code.

### Notebooks suffer from messiness
As you have probably already noticed, it is incredibly easy to make a complete mess of your Jupyter Notebook. They can become very difficult to follow especially if you do not document what is happening. There will be lots and lots of scratch work and cells that are broken.

### Out of order code execution
One built-in feature/problem with notebooks is that you can run any cell at any place at any time. In a normal computer program, control flows from one line to the next. With notebooks, you control which cell gets executed, so it is very easy to execute cells in a different order than their natural ordering. Furthermore, you can easily lose track of variable values.

## Know where Jupyter Notebook development ends and traditional software development begins
I only use Jupyter Notebooks whenever I am exploring data or need to write a formal report to someone. I typically use two notebooks, one for scratch work and another for my formal report. I ensure the formal notebook has the same behavior as a normal program by executing all the cells in order from the top. You can do this by using the option **Restart & Run All** from the **Kernel** menu or with the **Run All** option in the **Cell menu**.

# Must practice the commands
In this notebook we will practice some commands that will make your life programming in this environment much smoother.

## The three most common keyboard shortcuts A (above), B (below), DD (delete)
There are three keyboard shortcuts that you will use often and save you from reaching for your mouse. These are only possible while in **command mode**. Tap (don't hold) **ESC** to enter command mode. You will know you are in command mode when the outline of the cell is blue and there is no blinking cursor inside the cell.

* Press **A** to add a cell above
* Press **B** to add a cell below
* Press **DD** to delete a cell

## Press Enter - the simplest keyboard shortcut
While in command mode, simply press **enter**. This will switch you into edit mode in the current cell. The outer highlight will now turn **green**.

## Press h to see all the keyboard shortcuts
While in command mode, press **h** to pop up the menu of keyboard shortcuts. They are categorized by what mode they are used in - command or edit.
    
## Practice these shortcuts now 
Add and delete cells and enter them
    
[1]: https://colab.research.google.com/
[2]: http://jupyter.org/widgets
[3]: https://bokeh.pydata.org/en/latest/
[4]: https://plot.ly/products/dash/

In [2]:
import pandas as pd

In [5]:
bikes = pd.read_csv('../data/bikes.csv')
bikes.head()

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
0,7147,Subscriber,Male,2013-06-28 19:01:00,2013-06-28 19:17:00,993,Lake Shore Dr & Monroe St,41.881050,-87.616970,11.0,Michigan Ave & Oak St,41.900960,-87.623777,15.0,73.9,10.0,12.7,-9999.0,mostlycloudy
1,7524,Subscriber,Male,2013-06-28 22:53:00,2013-06-28 23:03:00,623,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wells St & Walton St,41.899930,-87.634430,19.0,69.1,10.0,6.9,-9999.0,partlycloudy
2,10927,Subscriber,Male,2013-06-30 14:43:00,2013-06-30 15:01:00,1040,Sheffield Ave & Kingsbury St,41.909592,-87.653497,15.0,Dearborn St & Monroe St,41.881320,-87.629521,23.0,73.0,10.0,16.1,-9999.0,mostlycloudy
3,12907,Subscriber,Male,2013-07-01 10:05:00,2013-07-01 10:16:00,667,Carpenter St & Huron St,41.894556,-87.653449,19.0,Clark St & Randolph St,41.884576,-87.631890,31.0,72.0,10.0,16.1,-9999.0,mostlycloudy
4,13168,Subscriber,Male,2013-07-01 11:16:00,2013-07-01 11:18:00,130,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,73.0,10.0,17.3,-9999.0,partlycloudy

In [7]:
bikes = bikes.set_index

AttributeError: 'function' object has no attribute 'set_index'

# The five step process when doing data exploration
To help increase your understanding of data and lessen your frustration fighting with Jupyter Notebooks, I recommend the following five step process:
1. Write and execute a single line of code to explore your data. Usually you are doing something to a DataFrame or a Series
1. Verify that this line of code works by inspecting the output
1. Assign the result to a variable
1. Within the same cell, in a second line output the head of the DataFrame or Series
1. Continue to the next cell. Do not add more lines of code to the cell

A major pain point for beginners is writing too many lines of code in a single cell. When you are learning, you need to get feedback on every single line of code that you write and verify that it is in fact correct. Only once you have verified the result should you move on to the next line of code.

# An example of this in action
We will do three separate tasks below:
* Read in the data
* Set the index
* Select the gender and tripduration columns

In [8]:
import pandas as pd

In [10]:
bikes = pd.read_csv('../data/bikes.csv')

In [11]:
bikes.head()

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
0,7147,Subscriber,Male,2013-06-28 19:01:00,2013-06-28 19:17:00,993,Lake Shore Dr & Monroe St,41.881050,-87.616970,11.0,Michigan Ave & Oak St,41.900960,-87.623777,15.0,73.9,10.0,12.7,-9999.0,mostlycloudy
1,7524,Subscriber,Male,2013-06-28 22:53:00,2013-06-28 23:03:00,623,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wells St & Walton St,41.899930,-87.634430,19.0,69.1,10.0,6.9,-9999.0,partlycloudy
2,10927,Subscriber,Male,2013-06-30 14:43:00,2013-06-30 15:01:00,1040,Sheffield Ave & Kingsbury St,41.909592,-87.653497,15.0,Dearborn St & Monroe St,41.881320,-87.629521,23.0,73.0,10.0,16.1,-9999.0,mostlycloudy
3,12907,Subscriber,Male,2013-07-01 10:05:00,2013-07-01 10:16:00,667,Carpenter St & Huron St,41.894556,-87.653449,19.0,Clark St & Randolph St,41.884576,-87.631890,31.0,72.0,10.0,16.1,-9999.0,mostlycloudy
4,13168,Subscriber,Male,2013-07-01 11:16:00,2013-07-01 11:18:00,130,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,73.0,10.0,17.3,-9999.0,partlycloudy

In [13]:
bikes.set_index('trip_id')

,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
trip_id,,,,,,,,,,,,,,,,,,
7147,Subscriber,Male,2013-06-28 19:01:00,2013-06-28 19:17:00,993,Lake Shore Dr & Monroe St,41.881050,-87.616970,11.0,Michigan Ave & Oak St,41.900960,-87.623777,15.0,73.9,10.0,12.7,-9999.00,mostlycloudy
7524,Subscriber,Male,2013-06-28 22:53:00,2013-06-28 23:03:00,623,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wells St & Walton St,41.899930,-87.634430,19.0,69.1,10.0,6.9,-9999.00,partlycloudy
10927,Subscriber,Male,2013-06-30 14:43:00,2013-06-30 15:01:00,1040,Sheffield Ave & Kingsbury St,41.909592,-87.653497,15.0,Dearborn St & Monroe St,41.881320,-87.629521,23.0,73.0,10.0,16.1,-9999.00,mostlycloudy
12907,Subscriber,Male,2013-07-01 10:05:00,2013-07-01 10:16:00,667,Carpenter St & Huron St,41.894556,-87.653449,19.0,Clark St & Randolph St,41.884576,-87.631890,31.0,72.0,10.0,16.1,-9999.00,mostlycloudy
13168,Subscriber,Male,2013-07-01 11:16:00,2013-07-01 11:18:00,130,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,73.0,10.0,17.3,-9999.00,partlycloudy
13595,Subscriber,Male,2013-07-01 12:37:00,2013-07-01 12:48:00,660,California Ave & 21st St,41.854016,-87.695445,15.0,Clark St & Wrightwood Ave,41.929546,-87.643118,15.0,73.0,10.0,17.3,-9999.00,mostlycloudy
18880,Subscriber,Male,2013-07-02 17:47:00,2013-07-02 17:56:00,565,Clark St & Randolph St,41.884576,-87.631890,31.0,Ravenswood Ave & Irving Park Rd,41.954690,-87.673930,19.0,66.0,10.0,15.0,-9999.00,cloudy
19689,Subscriber,Male,2013-07-03 09:07:00,2013-07-03 09:16:00,505,State St & Van Buren St,41.877181,-87.627844,27.0,Franklin St & Jackson Blvd,41.877708,-87.635321,27.0,64.0,7.0,5.8,-9999.00,cloudy
21028,Subscriber,Male,2013-07-03 15:21:00,2013-07-03 15:42:00,1300,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wood St & Division St,41.903320,-87.672730,15.0,71.1,8.0,0.0,-9999.00,cloudy
23558,Subscriber,Female,2013-07-04 15:00:00,2013-07-04 15:16:00,922,Lakeview Ave & Fullerton Pkwy,41.925858,-87.638973,19.0,Racine Ave & Congress Pkwy,41.874640,-87.657030,19.0,81.0,10.0,12.7,-9999.00,mostlycloudy
24383,Subscriber,Male,2013-07-04 17:17:00,2013-07-04 17:42:00,1523,Morgan St & 18th St,41.858086,-87.651073,15.0,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,79.0,10.0,9.2,-9999.00,mostlycloudy
24673,Subscriber,Male,2013-07-04 18:13:00,2013-07-04 18:42:00,1697,Ashland Ave & Armitage Ave,41.917859,-87.668919,15.0,Lincoln Ave & Armitage Ave,41.918273,-87.638116,19.0,79.0,10.0,10.4,-9999.00,mostlycloudy
26214,Subscriber,Male,2013-07-05 10:02:00,2013-07-05 10:40:00,2263,Jefferson St & Monroe St,41.880422,-87.642746,19.0,Jefferson St & Monroe St,41.880422,-87.642746,19.0,79.0,10.0,0.0,-9999.00,partlycloudy
30404,Subscriber,Male,2013-07-06 09:43:00,2013-07-06 10:06:00,1365,May St & Randolph St,41.883970,-87.655688,15.0,Millennium Park,41.881032,-87.624084,35.0,78.1,10.0,5.8,-9999.00,partlycloudy
31121,Subscriber,Female,2013-07-06 12:39:00,2013-07-06 12:49:00,610,Morgan St & Lake St,41.885483,-87.652305,15.0,Aberdeen St & Jackson Blvd,41.877726,-87.654787,15.0,82.0,10.0,5.8,-9999.00,mostlycloudy
33998,Subscriber,Male,2013-07-07 00:06:00,2013-07-07 00:13:00,415,Aberdeen St & Madison St,41.881487,-87.654752,19.0,May St & Taylor St,41.869482,-87.655486,15.0,72.0,10.0,5.8,-9999.00,mostlycloudy
38628,Subscriber,Male,2013-07-08 17:06:00,2013-07-08 17:14:00,487,Clinton St & Tilden St,41.875885,-87.640795,23.0,State St & Harrison St,41.873958,-87.627739,19.0,84.0,10.0,8.1,0.00,mostlycloudy
38729,Subscriber,Male,2013-07-08 17:33:00,2013-07-08 17:44:00,622,Larrabee St & Kingsbury St,41.897764,-87.642884,27.0,State St & Kinzie St,41.889180,-87.627700,15.0,84.0,10.0,8.1,0.00,mostlycloudy
40924,Subscriber,Male,2013-07-09 13:12:00,2013-07-09 14:42:00,5396,Canal St & Jackson Blvd,41.878114,-87.639971,35.0,Millennium Park,41.881032,-87.624084,35.0,79.0,10.0,13.8,0.00,cloudy
40879,Subscriber,Male,2013-07-09 13:14:00,2013-07-09 13:20:00,384,Aberdeen St & Madison St,41.881487,-87.654752,19.0,Canal St & Jackson Blvd,41.878114,-87.639971,35.0,79.0,10.0,13.8,0.00,cloudy
42488,Subscriber,Female,2013-07-09 17:39:00,2013-07-09 17:55:00,943,State St & Van Buren St,41.877181,-87.627844,27.0,State St & 16th St,41.860121,-87.627729,15.0,82.9,10.0,9.2,-9999.00,mostlycloudy
42818,Subscriber,Female,2013-07-09 19:26:00,2013-07-09 19:38:00,726,Clark St & Randolph St,41.884576,-87.631890,31.0,State St & Harrison St,41.873958,-87.627739,19.0,82.9,10.0,9.2,-9999.00,partlycloudy
43804,Subscriber,Female,2013-07-10 09:18:00,2013-07-10 09:33:00,895,Wells St & Walton St,41.899930,-87.634430,19.0,Ashland Ave & Augusta Blvd,41.899643,-87.667700,15.0,82.0,10.0,11.5,-9999.00,partlycloudy
45077,Subscriber,Female,2013-07-10 12:34:00,2013-07-10 12:46:00,700,Lincoln Ave & Armitage Ave,41.918273,-87.638116,19.0,Wilton Ave & Diversey Pkwy,41.932500,-87.652681,19.0,84.9,10.0,16.1,-9999.00,mostlycloudy
46108,Subscriber,Female,2013-07-10 16:35:00,2013-07-10 16:44:00,511,Michigan Ave & Lake St,41.886058,-87.624289,23.0,Clinton St & Madison St,41.881582,-87.641277,23.0,82.9,10.0,12.7,-9999.00,partlycloudy
47798,Subscriber,Female,2013-07-11 08:17:00,2013-07-11 08:31:00,830,Wabash Ave & Roosevelt Rd,41.867173,-87.625955,19.0,Daley Center Plaza,41.884337,-87.630183,47.0,73.9,10.0,8.1,-9999.00,clear
51130,Subscriber,Male,2013-07-12 01:07:00,2013-07-12 01:24:00,1043,State St & Harrison St,41.873958,-87.627739,19.0,Racine Ave & 18th St,41.858181,-87.656487,15.0,64.9,10.0,0.0,-9999.00,clear
51210,Subscriber,Male,2013-07-12 06:53:00,2013-07-12 07:00:00,439,Wabash Ave & Roosevelt Rd,41.867173,-87.625955,19.0,Dearborn St & Adams St,41.879356,-87.629791,19.0,64.9,10.0,0.0,-9999.00,partlycloudy
51823,Subscriber,Male,2013-07-12 10:01:00,2013-07-12 10:02:00,88,Daley Center Plaza,41.884337,-87.630183,47.0,Daley Center Plaza,41.884337,-87.630183,47.0,77.0,10.0,4.6,-9999.00,partlycloudy
52547,Subscriber,Male,2013-07-12 12:23:00,2013-07-12 12:28:00,294,Michigan Ave & Lake St,41.886058,-87.624289,23.0,Daley Center Plaza,41.884337,-87.630183,47.0,81.0,10.0,4.6,-9999.00,partlycloudy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17525739,Subscriber,Male,2017-12-23 15:28:00,2017-12-23 15:34:00,389,Marshfield Ave & Cortland St,41.916017,-87.668879,23.0,Leavitt St & Armitage Ave,41.917805,-87.682437,11.0,26.1,10.0,11.5,-9999.00,partlycloudy
17525743,Subscriber,Male,2017-12-23 15:31:00,2017-12-23 15:38:00,412,Western Ave & Winnebago Ave,41.915520,-87.687022,15.0,Spaulding Ave & Armitage Ave,41.917184,-87.710357,15.0,26.1,10.0,11.5,-9999.00,partlycloudy
17526542,Subscriber,Female,2017-12-24 07:56:00,2017-12-24 07:59:00,183,Hampden Ct & Diversey Pkwy,41.932620,-87.642385,23.0,Wilton Ave & Diversey Pkwy,41.932418,-87.652705,27.0,21.0,10.0,6.9,-9999.00,cloudy
17527722,Subscriber,Male,2017-12-25 18:31:00,2017-12-25 18:38:00,389,Dayton St & North Ave,41.910578,-87.649422,19.0,Larrabee St & Oak St,41.900219,-87.642985,19.0,10.0,10.0,6.9,-9999.00,partlycloudy
17528311,Subscriber,Male,2017-12-26 13:27:00,2017-12-26 13:35:00,493,Washtenaw Ave & Lawrence Ave,41.968987,-87.696027,15.0,Ravenswood Ave & Lawrence Ave,41.969090,-87.674237,39.0,3.9,10.0,12.7,-9999.00,mostlycloudy
17528461,Subscriber,Male,2017-12-26 15:09:00,2017-12-26 15:19:00,583,Racine Ave (May St) & Fulton St,41.886926,-87.656919,15.0,Canal St & Adams St,41.879255,-87.639904,47.0,3.9,10.0,11.5,-9999.00,partlycloudy
17528527,Subscriber,Male,2017-12-26 15:49:00,2017-12-26 15:56:00,369,Lincoln Ave & Diversey Pkwy,41.932225,-87.658617,15.0,Clark St & Wrightwood Ave,41.929546,-87.643118,15.0,3.9,10.0,11.5,-9999.00,partlycloudy
17528614,Subscriber,Male,2017-12-26 16:34:00,2017-12-26 16:46:00,705,Clinton St & Lake St,41.885637,-87.641823,23.0,Ogden Ave & Chicago Ave,41.896362,-87.654061,19.0,3.0,10.0,9.2,-9999.00,partlycloudy
17529175,Subscriber,Male,2017-12-27 06:05:00,2017-12-27 06:07:00,138,Wabash Ave & Roosevelt Rd,41.867227,-87.625961,23.0,Michigan Ave & 14th St,41.864059,-87.623727,19.0,-2.9,10.0,11.5,-9999.00,partlycloudy
17529292,Subscriber,Male,2017-12-27 07:46:00,2017-12-27 08:00:00,856,Canal St & Adams St,41.879255,-87.639904,47.0,Dearborn Pkwy & Delaware Pl,41.898969,-87.629912,19.0,-2.9,10.0,8.1,-9999.00,partlycloudy
17529402,Subscriber,Male,2017-12-27 08:34:00,2017-12-27 08:38:00,227,LaSalle St & Illinois St,41.890762,-87.631697,31.0,Fairbanks Ct & Grand Ave,41.891860,-87.620620,15.0,-0.9,10.0,8.1,-9999.00,partlycloudy
17530881,Subscriber,Male,2017-12-27 20:02:00,2017-12-27 20:06:00,275,Halsted St & Roscoe St,41.943670,-87.648950,15.0,Clark St & Wellington Ave,41.936497,-87.647539,15.0,1.0,10.0,0.0,-9999.00,partlycloudy
17530946,Subscriber,Female,2017-12-27 21:08:00,2017-12-27 21:22:00,867,Western Ave & Walton St,41.898418,-87.686596,19.0,Damen Ave & Augusta Blvd,41.899113,-87.677212,23.0,1.0,10.0,4.6,-9999.00,partlycloudy
17531067,Subscriber,Male,2017-12-28 06:16:00,2017-12-28 06:22:00,392,State St & Randolph St,41.884730,-87.627734,27.0,McClurg Ct & Illinois St,41.890359,-87.617532,31.0,5.0,10.0,0.0,-9999.00,cloudy
17531700,Subscriber,Male,2017-12-28 10:27:00,2017-12-28 10:34:00,401,Sheffield Ave & Willow St,41.913688,-87.652855,15.0,Clybourn Ave & Division St,41.904613,-87.640552,15.0,12.9,10.0,10.4,-9999.00,cloudy
17532063,Subscriber,Male,2017-12-28 13:08:00,2017-12-28 13:13:00,258,Ashland Ave & Chicago Ave,41.895966,-87.667747,15.0,Ashland Ave & Division St,41.903450,-87.667747,19.0,12.9,6.0,9.2,0.00,snow
17532624,Subscriber,Male,2017-12-28 17:03:00,2017-12-28 17:07:00,226,Wabash Ave & Wacker Pl,41.886875,-87.626030,19.0,State St & Randolph St,41.884730,-87.627734,27.0,12.0,2.0,8.1,0.01,snow
17533419,Subscriber,Male,2017-12-29 08:42:00,2017-12-29 08:48:00,356,Blackstone Ave & Hyde Park Blvd,41.802562,-87.590368,19.0,Lake Park Ave & 56th St,41.793242,-87.587782,19.0,10.9,8.0,4.6,-9999.00,cloudy
17533484,Subscriber,Male,2017-12-29 09:13:00,2017-12-29 09:53:00,2378,Clinton St & 18th St,41.857950,-87.640826,15.0,Canal St & Taylor St,41.870257,-87.639474,15.0,12.9,9.0,4.6,-9999.00,cloudy
17533656,Subscriber,Female,2017-12-29 11:14:00,2017-12-29 11:28:00,877,Southport Ave & Waveland Ave,41.948150,-87.663940,23.0,Clarendon Ave & Gordon Ter,41.957879,-87.649519,15.0,14.0,10.0,5.8,-9999.00,cloudy
17533757,Subscriber,Male,2017-12-29 12:08:00,2017-12-29 12:12:00,270,Southport Ave & Belmont Ave,41.939490,-87.663780,15.0,Wilton Ave & Belmont Ave,41.940180,-87.653040,23.0,14.0,2.5,6.9,0.00,snow
17534057,Subscriber,Male,2017-12-29 15:28:00,2017-12-29 15:51:00,1378,Cityfront Plaza Dr & Pioneer Ct,41.890573,-87.622072,23.0,Mies van der Rohe Way & Chestnut St,41.898587,-87.621915,19.0,14.0,1.5,6.9,0.01,snow
17534131,Subscriber,Male,2017-12-29 16:09:00,2017-12-29 16:19:00,617,Kingsbury St & Erie St,41.893882,-87.641711,23.0,Canal St & Adams St,41.879255,-87.639904,47.0,14.0,1.5,6.9,0.00,snow
17534773,Subscriber,Male,2017-12-30 10:47:00,2017-12-30 10:53:00,363,Larrabee St & Oak St,41.900219,-87.642985,19.0,Halsted St & Blackhawk St (*),41.908537,-87.648627,20.0,3.9,10.0,13.8,-9999.00,mostlycloudy
17534831,Subscriber,Male,2017-12-30 11:36:00,2017-12-30 11:55:00,1175,Western Ave & Walton St,41.898418,-87.686596,19.0,Damen Ave & Clybourn Ave,41.931931,-87.677856,15.0,3.9,10.0,13.8,-9999.00,partlycloudy
17534938,Subscriber,Male,2017-12-30 13:07:00,2017-12-30 13:34:00,1625,State St & Pearson St,41.897448,-87.628722,27.0,Clark St & Elm St,41.902973,-87.631280,27.0,5.0,10.0,16.1,-9999.00,partlycloudy
17534969,Subscriber,Male,2017-12-30 13:34:00,2017-12-30 13:44:00,585,Halsted St & 35th St (*),41.830661,-87.647172,16.0,Union Ave & Root St,41.819102,-87.643278,11.0,5.0,10.0,16.1,-9999.00,partlycloudy
17534972,Subscriber,Male,2017-12-30 13:34:00,2017-12-30 13:48:00,824,Kingsbury St & Kinzie St,41.889177,-87.638506,31.0,Halsted St & Blackhawk St (*),41.908537,-87.648627,20.0,5.0,10.0,16.1,-9999.00,partlycloudy
17535645,Subscriber,Female,2017-12-31 09:30:00,2017-12-31 09:33:00,178,Clinton St & Lake St,41.885637,-87.641823,23.0,Kingsbury St & Kinzie St,41.889177,-87.638506,31.0,7.0,10.0,11.5,-9999.00,partlycloudy
17536246,Subscriber,Male,2017-12-31 15:22:00,2017-12-31 15:26:00,214,Clarendon Ave & Leland Ave,41.967968,-87.650001,15.0,Clifton Ave & Lawrence Ave,41.968812,-87.657659,15.0,10.9,10.0,15.0,-9999.00,partlycloudy

In [14]:
bikes.head()

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
0,7147,Subscriber,Male,2013-06-28 19:01:00,2013-06-28 19:17:00,993,Lake Shore Dr & Monroe St,41.881050,-87.616970,11.0,Michigan Ave & Oak St,41.900960,-87.623777,15.0,73.9,10.0,12.7,-9999.0,mostlycloudy
1,7524,Subscriber,Male,2013-06-28 22:53:00,2013-06-28 23:03:00,623,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wells St & Walton St,41.899930,-87.634430,19.0,69.1,10.0,6.9,-9999.0,partlycloudy
2,10927,Subscriber,Male,2013-06-30 14:43:00,2013-06-30 15:01:00,1040,Sheffield Ave & Kingsbury St,41.909592,-87.653497,15.0,Dearborn St & Monroe St,41.881320,-87.629521,23.0,73.0,10.0,16.1,-9999.0,mostlycloudy
3,12907,Subscriber,Male,2013-07-01 10:05:00,2013-07-01 10:16:00,667,Carpenter St & Huron St,41.894556,-87.653449,19.0,Clark St & Randolph St,41.884576,-87.631890,31.0,72.0,10.0,16.1,-9999.0,mostlycloudy
4,13168,Subscriber,Male,2013-07-01 11:16:00,2013-07-01 11:18:00,130,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,73.0,10.0,17.3,-9999.0,partlycloudy

# Details
When coding this live, you would not assign the results to a variable immediately. For instance, in the second step, you might first write `bikes.set_index('trip_id')`. This would produce some output which you would verify. Once verified, then the assignment statement would be created. And finally the head of DataFrame would be outputted.

# When to assign the result to a variable
Not all operations on our data will need to be assigned to a variable. We might just be interested in seeing the results. But, for many operations, you will want to continue with the new transformed data. By assigning the result to a variable, you have immediate access to the previous result.

# When to create a new variable name
In the second cell, `bikes` was reassigned to itself. We did this because we no longer needed the original DataFrame. In the third cell, we created an entire new variable. This was done because we wanted to keep the `bikes` DataFrame. Creating new variables also makes it easier to trace the flow of work. Debugging is easier as well, since we will have preserved the result of the cell in its own variable (assuming we did not overwrite it in a later cell).

# Continuously verifying results
Regardless of how adept you become at doing data explorations, it is good practice to verify each line of code. Data science is difficult and it is easy to make mistakes. Data is also messy and it is good to be skeptical while proceeding through an analysis. Getting a visual verification that each line of code is producing the desired result is important. Doing this also provides feedback to help you think about what avenues to explore next.

# Execute cells with alt + enter to insert a new cell when doing exercises
The exercises at the bottom of each notebook only have a single cell between them. This is usually not enough room to complete it. Normally we we execute cells with **shift + enter**. This will move you to the next cell, even if it has content in it and put you in command mode as well. Since the next cell will be another exercise problem this won't be the position you desire.

Instead, execute the cell by pressing **alt + enter** or **option + enter**. This will execute the cell and insert a new cell after it. It will also keep you in edit mode. This is exactly what you want when doing the exercises.

Alternatively, you can press **shit + enter** and then press **A** to insert a new cell above and finally press enter to go into edit mode. Either way will work.

## Practice alt + enter below

### Problem 1
<span  style="color:green; font-size:16px">Assign some number to `a` in one cell. In the next 5 cells, add some number to it and assign the result to a new variable. Make sure to output the value of the new variable.</span>

In [ ]:
# your code here

### Problem 2
<span  style="color:green; font-size:16px">Some problem here that is in the way!</span>