# 9. Boolean Indexing Multiple Conditions

### Objectives

+ Create complex filters with the and (**`&`**), or (**`|`**), and not (**`~`**) logical operators
+ Wrap each filter with parentheses when more than one occur at the same line
+ For readability, assign each filter to its own variable
+ Use the **`isin`** method to test for multiple equalities in the same column

## Multiple condition expression
So far, our boolean selections have involved a single condition. You can have as many conditions as you would like. To do so, you will need to combine your boolean expressions using the three logical operators and, or, and not.

## Use `&`, `|` , `~`
Although Python uses the keywords `and`, `or`, and `not`, these will not work when with Pandas. 

You must use the following operators:

* **`&`** for and
* **`|`** for or
* **`~`** for not

## Our first multiple condition expression
Let's find all the rides longer than 1,000 seconds when it was cloudy. We assign each condition to separate variables and then combine them with the and operator.

In [1]:
import pandas as pd
bikes = pd.read_csv('../data/bikes.csv')

In [2]:
filt1 = bikes['tripduration'] > 1000
filt2 = bikes['events'] == 'cloudy'
filt = filt1 & filt2

bikes[filt].head(3)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
8,21028,Subscriber,Male,2013-07-03 15:21:00,2013-07-03 15:42:00,1300,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wood St & Division St,41.903320,-87.672730,15.0,71.1,8.0,0.0,-9999.0,cloudy
18,40924,Subscriber,Male,2013-07-09 13:12:00,2013-07-09 14:42:00,5396,Canal St & Jackson Blvd,41.878114,-87.639971,35.0,Millennium Park,41.881032,-87.624084,35.0,79.0,10.0,13.8,0.0,cloudy
80,90932,Subscriber,Female,2013-07-22 07:59:00,2013-07-22 08:19:00,1224,Lincoln Ave & Armitage Ave,41.918273,-87.638116,19.0,Dearborn St & Adams St,41.879356,-87.629791,19.0,73.4,10.0,0.0,-9999.0,cloudy

In [17]:
filt

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
50059    False
50060    False
50061    False
50062    False
50063    False
50064    False
50065    False
50066    False
50067    False
50068    False
50069    False
50070    False
50071    False
50072    False
50073    False
50074    False
50075    False
50076    False
50077    False
50078    False
50079    False
50080    False
50081    False
50082    False
50083    False
50084    False
50085    False
50086    False
50087    False
50088    False
Length: 50089, dtype: bool

## Multiple conditions in one line
It is possible to combine the entire expression into a single line. Many pandas users like doing this, others hate it. Regardless, it is a good idea to know how to do so as you will definitely encounter it.

## Use parentheses to separate conditions
You must encapsulate each condition in a set of parentheses in order to make this work.

Each condition will be separated like this:

```

(bikes['tripduration'] > 1000) & (bikes['events'] == 'cloudy')

```

## Same results
We can then drop this expression inside of just the indexing operator to get the same results:

In [3]:
bikes[(bikes['tripduration'] > 1000) & (bikes['events'] == 'cloudy')].head(3)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
8,21028,Subscriber,Male,2013-07-03 15:21:00,2013-07-03 15:42:00,1300,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wood St & Division St,41.903320,-87.672730,15.0,71.1,8.0,0.0,-9999.0,cloudy
18,40924,Subscriber,Male,2013-07-09 13:12:00,2013-07-09 14:42:00,5396,Canal St & Jackson Blvd,41.878114,-87.639971,35.0,Millennium Park,41.881032,-87.624084,35.0,79.0,10.0,13.8,0.0,cloudy
80,90932,Subscriber,Female,2013-07-22 07:59:00,2013-07-22 08:19:00,1224,Lincoln Ave & Armitage Ave,41.918273,-87.638116,19.0,Dearborn St & Adams St,41.879356,-87.629791,19.0,73.4,10.0,0.0,-9999.0,cloudy

## Again, I prefer assigning each condition to its own variable

## Using an `or` condition
Let's find all the rides that were done by females **or** had trip durations longer than 1,000 seconds.

For the or condition, we use the pipe character **`|`**

In [4]:
filt1 = bikes['tripduration'] > 1000
filt2 = bikes['gender'] == 'Female'
filt = filt1 | filt2

bikes[filt].head(3)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
2,10927,Subscriber,Male,2013-06-30 14:43:00,2013-06-30 15:01:00,1040,Sheffield Ave & Kingsbury St,41.909592,-87.653497,15.0,Dearborn St & Monroe St,41.88132,-87.629521,23.0,73.0,10.0,16.1,-9999.0,mostlycloudy
8,21028,Subscriber,Male,2013-07-03 15:21:00,2013-07-03 15:42:00,1300,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wood St & Division St,41.90332,-87.672730,15.0,71.1,8.0,0.0,-9999.0,cloudy
9,23558,Subscriber,Female,2013-07-04 15:00:00,2013-07-04 15:16:00,922,Lakeview Ave & Fullerton Pkwy,41.925858,-87.638973,19.0,Racine Ave & Congress Pkwy,41.87464,-87.657030,19.0,81.0,10.0,12.7,-9999.0,mostlycloudy

## Reversing a condition with the not operator
The tilde character, **`~`**, represents the not operator and reverses a condition.  For instance, if we wanted all the rides with trip duration less than or equal to 1000, we could do it like this:

In [5]:
filt = bikes['tripduration'] > 1000
bikes[~filt].head(3)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
0,7147,Subscriber,Male,2013-06-28 19:01:00,2013-06-28 19:17:00,993,Lake Shore Dr & Monroe St,41.881050,-87.616970,11.0,Michigan Ave & Oak St,41.900960,-87.623777,15.0,73.9,10.0,12.7,-9999.0,mostlycloudy
1,7524,Subscriber,Male,2013-06-28 22:53:00,2013-06-28 23:03:00,623,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wells St & Walton St,41.899930,-87.634430,19.0,69.1,10.0,6.9,-9999.0,partlycloudy
3,12907,Subscriber,Male,2013-07-01 10:05:00,2013-07-01 10:16:00,667,Carpenter St & Huron St,41.894556,-87.653449,19.0,Clark St & Randolph St,41.884576,-87.631890,31.0,72.0,10.0,16.1,-9999.0,mostlycloudy

Of course, reversing single conditions is pretty pointless as we can simply use the less than or equal to operator instead like this:

In [6]:
filt = bikes['tripduration'] <= 1000
bikes[filt].head(3)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
0,7147,Subscriber,Male,2013-06-28 19:01:00,2013-06-28 19:17:00,993,Lake Shore Dr & Monroe St,41.881050,-87.616970,11.0,Michigan Ave & Oak St,41.900960,-87.623777,15.0,73.9,10.0,12.7,-9999.0,mostlycloudy
1,7524,Subscriber,Male,2013-06-28 22:53:00,2013-06-28 23:03:00,623,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wells St & Walton St,41.899930,-87.634430,19.0,69.1,10.0,6.9,-9999.0,partlycloudy
3,12907,Subscriber,Male,2013-07-01 10:05:00,2013-07-01 10:16:00,667,Carpenter St & Huron St,41.894556,-87.653449,19.0,Clark St & Randolph St,41.884576,-87.631890,31.0,72.0,10.0,16.1,-9999.0,mostlycloudy

### Reverse a more complex condition
Typically, we will save the not operator for reversing more complex conditions. Let's reverse the condition for selecting rides by females or those with duration over 1,000 seconds. Logically, this should return only male riders with duration 1,000 or less.

In [7]:
filt1 = bikes['tripduration'] > 1000
filt2 = bikes['gender'] == 'Female'
filt = filt1 | filt2

bikes[~filt].head(3)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
0,7147,Subscriber,Male,2013-06-28 19:01:00,2013-06-28 19:17:00,993,Lake Shore Dr & Monroe St,41.881050,-87.616970,11.0,Michigan Ave & Oak St,41.900960,-87.623777,15.0,73.9,10.0,12.7,-9999.0,mostlycloudy
1,7524,Subscriber,Male,2013-06-28 22:53:00,2013-06-28 23:03:00,623,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wells St & Walton St,41.899930,-87.634430,19.0,69.1,10.0,6.9,-9999.0,partlycloudy
3,12907,Subscriber,Male,2013-07-01 10:05:00,2013-07-01 10:16:00,667,Carpenter St & Huron St,41.894556,-87.653449,19.0,Clark St & Randolph St,41.884576,-87.631890,31.0,72.0,10.0,16.1,-9999.0,mostlycloudy

## Even more complex conditions
It is possible to build extremely complex conditions to select rows of your DataFrame that meet a very specific condition. For instance, we can select males riders with trip duration between 1,000 and 2,000 seconds along with female riders with trip duration betwee 5,000 and 10,000 seconds.

With multiple conditions, its probably best to break out the logic into multiple steps:

In [8]:
filt1 = (bikes['gender'] == 'Male') & (bikes['tripduration'] >= 1000) & (bikes['tripduration'] <= 2000)
filt2 = (bikes['gender'] == 'Female') & (bikes['tripduration'] >= 5000) & (bikes['tripduration'] <= 10000)
filt = filt1 | filt2

bikes[filt].head(10)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
2,10927,Subscriber,Male,2013-06-30 14:43:00,2013-06-30 15:01:00,1040,Sheffield Ave & Kingsbury St,41.909592,-87.653497,15.0,Dearborn St & Monroe St,41.881320,-87.629521,23.0,73.0,10.0,16.1,-9999.0,mostlycloudy
8,21028,Subscriber,Male,2013-07-03 15:21:00,2013-07-03 15:42:00,1300,Clinton St & Washington Blvd,41.883380,-87.641170,31.0,Wood St & Division St,41.903320,-87.672730,15.0,71.1,8.0,0.0,-9999.0,cloudy
10,24383,Subscriber,Male,2013-07-04 17:17:00,2013-07-04 17:42:00,1523,Morgan St & 18th St,41.858086,-87.651073,15.0,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,79.0,10.0,9.2,-9999.0,mostlycloudy
11,24673,Subscriber,Male,2013-07-04 18:13:00,2013-07-04 18:42:00,1697,Ashland Ave & Armitage Ave,41.917859,-87.668919,15.0,Lincoln Ave & Armitage Ave,41.918273,-87.638116,19.0,79.0,10.0,10.4,-9999.0,mostlycloudy
13,30404,Subscriber,Male,2013-07-06 09:43:00,2013-07-06 10:06:00,1365,May St & Randolph St,41.883970,-87.655688,15.0,Millennium Park,41.881032,-87.624084,35.0,78.1,10.0,5.8,-9999.0,partlycloudy
26,51130,Subscriber,Male,2013-07-12 01:07:00,2013-07-12 01:24:00,1043,State St & Harrison St,41.873958,-87.627739,19.0,Racine Ave & 18th St,41.858181,-87.656487,15.0,64.9,10.0,0.0,-9999.0,clear
34,54257,Subscriber,Male,2013-07-12 18:13:00,2013-07-12 18:40:00,1616,Clinton St & Madison St,41.881582,-87.641277,23.0,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,78.1,10.0,10.4,-9999.0,partlycloudy
40,61401,Subscriber,Female,2013-07-14 14:08:00,2013-07-14 15:53:00,6274,Wabash Ave & Roosevelt Rd,41.867173,-87.625955,19.0,Lake Shore Dr & Monroe St,41.881050,-87.616970,11.0,87.1,10.0,8.1,-9999.0,partlycloudy
41,64257,Subscriber,Male,2013-07-15 06:26:00,2013-07-15 06:44:00,1125,Racine Ave & Fullerton Ave,41.925563,-87.658404,19.0,State St & Kinzie St,41.889180,-87.627700,15.0,73.9,10.0,0.0,-9999.0,partlycloudy
47,67013,Subscriber,Male,2013-07-15 19:10:00,2013-07-15 19:34:00,1463,Lake Shore Dr & Ohio St,41.892570,-87.614492,19.0,Lake Shore Dr & Ohio St,41.892570,-87.614492,19.0,80.1,10.0,6.9,-9999.0,mostlycloudy

## Lots of equality conditions in a single column - use `isin`
Occasionally, we will want to test equality in a single column with multiple values. This is most common in string columns. For instance, let’s say we wanted to find all the rides where the events were either rain, snow, tstorms or sleet.

One way to do this would be with four or conditions.

In [9]:
filt = ((bikes['events'] == 'rain') | 
        (bikes['events'] == 'snow') | 
        (bikes['events'] == 'tstorms') | 
        (bikes['events'] == 'sleet'))

bikes[filt].head(3)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
45,66336,Subscriber,Male,2013-07-15 16:43:00,2013-07-15 16:55:00,727,Greenwood Ave & 47th St,41.809835,-87.599383,15.0,State St & Harrison St,41.873958,-87.627739,19.0,82.9,10.0,5.8,0.0,rain
78,89180,Subscriber,Male,2013-07-21 16:35:00,2013-07-21 17:06:00,1809,Michigan Ave & Pearson St,41.897660,-87.623510,23.0,Millennium Park,41.881032,-87.624084,35.0,82.4,10.0,11.5,0.0,tstorms
79,89228,Subscriber,Male,2013-07-21 16:47:00,2013-07-21 17:03:00,999,Carpenter St & Huron St,41.894556,-87.653449,19.0,Carpenter St & Huron St,41.894556,-87.653449,19.0,82.4,10.0,11.5,0.0,tstorms

Instead, use the **`isin`** method and pass it a list of all the acceptable values:

In [10]:
filt = bikes['events'].isin(['rain', 'snow', 'tstorms', 'sleet'])
bikes[filt].head(3)

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
45,66336,Subscriber,Male,2013-07-15 16:43:00,2013-07-15 16:55:00,727,Greenwood Ave & 47th St,41.809835,-87.599383,15.0,State St & Harrison St,41.873958,-87.627739,19.0,82.9,10.0,5.8,0.0,rain
78,89180,Subscriber,Male,2013-07-21 16:35:00,2013-07-21 17:06:00,1809,Michigan Ave & Pearson St,41.897660,-87.623510,23.0,Millennium Park,41.881032,-87.624084,35.0,82.4,10.0,11.5,0.0,tstorms
79,89228,Subscriber,Male,2013-07-21 16:47:00,2013-07-21 17:03:00,999,Carpenter St & Huron St,41.894556,-87.653449,19.0,Carpenter St & Huron St,41.894556,-87.653449,19.0,82.4,10.0,11.5,0.0,tstorms

## Combining isin with other filters
You can use the resulting boolean Series from the isin method in the same way you would from the logical operators. For instance, If we wanted to find all the rides that had the same events and had a duration greater than 10,000 we would do the following:

In [11]:
filt1 = bikes['events'].isin(['rain', 'snow', 'tstorms', 'sleet'])
filt2 = bikes['tripduration'] > 2000
filt = filt1 & filt2

bikes[filt].head()

,trip_id,usertype,gender,starttime,stoptime,tripduration,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_name,latitude_end,longitude_end,dpcapacity_end,temperature,visibility,wind_speed,precipitation,events
2344,1266453,Subscriber,Female,2014-03-19 07:23:00,2014-03-19 08:00:00,2181,Seeley Ave & Roscoe St,41.943403,-87.679618,11.0,Franklin St & Lake St,41.885837,-87.635500,23.0,43.0,3.0,6.9,0.07,rain
7697,3557596,Subscriber,Male,2014-09-12 14:20:00,2014-09-12 14:57:00,2213,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,California Ave & Division St,41.903029,-87.697474,15.0,52.0,2.0,12.7,0.00,rain
8357,3801419,Subscriber,Male,2014-09-30 08:21:00,2014-09-30 08:58:00,2246,Damen Ave & Melrose Ave,41.940600,-87.678500,11.0,Wood St & Taylor St,41.869154,-87.671045,15.0,46.9,3.0,11.5,0.00,rain
8506,3846762,Subscriber,Male,2014-10-04 12:33:00,2014-10-04 14:06:00,5568,Halsted St & Diversey Pkwy,41.933341,-87.648747,15.0,Halsted St & Wrightwood Ave,41.929143,-87.649077,15.0,42.1,8.0,17.3,0.02,rain
11267,4822906,Subscriber,Male,2015-04-10 17:25:00,2015-04-10 18:00:00,2074,Stetson Ave & South Water St,41.886835,-87.622320,19.0,Lake Shore Dr & Wellington Ave,41.936669,-87.636794,15.0,46.9,10.0,17.3,0.00,rain

# Exercises

### Problem 1
<span  style="color:green; font-size:16px">Select all movies from the 1970s that had IMDB scores greater than 8</span>

In [18]:
# your code here
import pandas as pd

In [20]:
movie = pd.read_csv('../data/movie.csv')
movie.head(3)

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8

In [21]:
filt1 = movie['year'] >= 1970
filt2 = movie['year'] < 1980
filt3 = movie['imdb_score'] > 8
filt = filt1 & filt2 & filt3 
movie[filt].head(5)

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
1052,Solaris,1972.0,Black and White,PG,115.0,Andrei Tarkovsky,0.0,Donatas Banionis,29.0,Anatoliy Solonitsyn,...,12.0,NaN,Drama|Mystery|Sci-Fi,144.0,54057,hallucination|ocean|psychologist|scientist|spa...,Russian,Soviet Union,1000000.0,8.1
1556,Apocalypse Now,1979.0,Color,R,289.0,Francis Ford Coppola,0.0,Harrison Ford,11000.0,Marlon Brando,...,3000.0,78800000.0,Drama|War,261.0,450676,army|green beret|insanity|jungle|vietnam,English,USA,31500000.0,8.5
2591,The Deer Hunter,1978.0,Color,R,183.0,Michael Cimino,517.0,Robert De Niro,22000.0,Meryl Streep,...,652.0,NaN,Drama|War,140.0,232577,escape|friend|party|pittsburgh steelers|vietnam,English,UK,15000000.0,8.2
2791,The Godfather: Part II,1974.0,Color,R,220.0,Francis Ford Coppola,0.0,Robert De Niro,22000.0,Al Pacino,...,3000.0,57300000.0,Crime|Drama,149.0,790926,1950s|corrupt politician|lake tahoe nevada|mel...,English,USA,13000000.0,9.0
2973,Star Wars: Episode IV - A New Hope,1977.0,Color,PG,125.0,George Lucas,0.0,Harrison Ford,11000.0,Peter Cushing,...,504.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,282.0,911097,death star|empire|galactic war|princess|rebellion,English,USA,11000000.0,8.7

### Problem 2
<span  style="color:green; font-size:16px">Select movies that were rated either R, PG-13, or PG.</span>

In [22]:
# your code here
content_rate = ['R', 'RG-13', 'PG']
filt = movie['content_rating'].isin(content_rate)
movie[filt]

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
7,Tangled,2010.0,Color,PG,100.0,Nathan Greno,15.0,Brad Garrett,799.0,Donna Murphy,...,284.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,324.0,294810,17th century|based on fairy tale|disney|flower...,English,USA,260000000.0,7.8
9,Harry Potter and the Half-Blood Prince,2009.0,Color,PG,153.0,David Yates,282.0,Alan Rickman,25000.0,Daniel Radcliffe,...,10000.0,301956980.0,Adventure|Family|Fantasy|Mystery,375.0,321795,blood|book|love|potion|professor,English,UK,250000000.0,7.5
16,The Chronicles of Narnia: Prince Caspian,2008.0,Color,PG,150.0,Andrew Adamson,80.0,Peter Dinklage,22000.0,Pierfrancesco Favino,...,201.0,141614023.0,Action|Adventure|Family|Fantasy,258.0,149922,brother brother relationship|brother sister re...,English,USA,225000000.0,6.6
33,Alice in Wonderland,2010.0,Color,PG,108.0,Tim Burton,13000.0,Johnny Depp,40000.0,Alan Rickman,...,11000.0,334185206.0,Adventure|Family|Fantasy,451.0,306320,alice in wonderland|mistaking reality for drea...,English,USA,200000000.0,6.5
38,Oz the Great and Powerful,2013.0,Color,PG,130.0,Sam Raimi,0.0,Tim Holmes,44000.0,Mila Kunis,...,11000.0,234903076.0,Adventure|Family|Fantasy,525.0,175409,circus|magic|magician|oz|witch,English,USA,215000000.0,6.4
40,TRON: Legacy,2010.0,Color,PG,125.0,Joseph Kosinski,364.0,Jeff Bridges,12000.0,Olivia Wilde,...,1000.0,172051787.0,Action|Adventure|Sci-Fi,469.0,264183,arcade|bridge|disappearance|escape|warrior,English,USA,170000000.0,6.8
55,The Good Dinosaur,2015.0,Color,PG,93.0,Peter Sohn,113.0,A.J. Buckley,275.0,Jack McGraw,...,113.0,123070338.0,Adventure|Animation|Comedy|Family|Fantasy,298.0,62836,apatosaurus|asteroid|dinosaur|fear|river,English,USA,NaN,6.8
56,Brave,2012.0,Color,PG,93.0,Mark Andrews,56.0,Kelly Macdonald,2000.0,John Ratzenberger,...,838.0,237282182.0,Adventure|Animation|Comedy|Family|Fantasy,488.0,273556,archery|coming of age|female warrior|princess|...,English,USA,185000000.0,7.2
61,A Christmas Carol,2009.0,Color,PG,96.0,Robert Zemeckis,0.0,Robin Wright,18000.0,Colin Firth,...,10000.0,137850096.0,Animation|Drama|Family|Fantasy,240.0,72809,charles dickens|christmas|christmas eve|ghost|...,English,USA,200000000.0,6.8
64,"The Chronicles of Narnia: The Lion, the Witch ...",2005.0,Color,PG,150.0,Andrew Adamson,80.0,Jim Broadbent,1000.0,Kiran Shah,...,82.0,291709845.0,Adventure|Family|Fantasy,284.0,286506,hide and seek|lion|magic|professor|snow,English,USA,180000000.0,6.9
67,Up,2009.0,Color,PG,96.0,Pete Docter,0.0,John Ratzenberger,1000.0,Delroy Lindo,...,262.0,292979556.0,Adventure|Animation|Comedy|Family,408.0,665575,balloon|house|promise|retirement|skeleton,English,USA,175000000.0,8.3
68,Monsters vs. Aliens,2009.0,Color,PG,94.0,Rob Letterman,11.0,Amy Poehler,1000.0,Rainn Wilson,...,459.0,198332128.0,Action|Adventure|Animation|Comedy|Family|Sci-Fi,219.0,114553,alien|alien invasion|alien space craft|giant|g...,English,USA,175000000.0,6.5
70,Hugo,2011.0,Color,PG,126.0,Martin Scorsese,17000.0,Chloë Grace Moretz,17000.0,Christopher Lee,...,1000.0,73820094.0,Adventure|Drama|Family|Mystery,682.0,245333,automaton|mechanical|railway station|steampunk...,English,USA,170000000.0,7.5
74,Evan Almighty,2007.0,Color,PG,96.0,Tom Shadyac,293.0,Jimmy Bennett,87000.0,Morgan Freeman,...,7000.0,100289690.0,Comedy|Family|Fantasy,186.0,115099,ark|change|congressman|depiction of god|flood,English,USA,175000000.0,5.4
78,Inside Out,2015.0,Color,PG,95.0,Pete Docter,0.0,Amy Poehler,1000.0,Mindy Kaling,...,384.0,356454367.0,Adventure|Animation|Comedy|Drama|Family|Fantasy,536.0,345198,anger|joy|memory|running away|sadness,English,USA,175000000.0,8.3
79,The Jungle Book,2016.0,Color,PG,106.0,Jon Favreau,4000.0,Scarlett Johansson,19000.0,Bill Murray,...,591.0,362645141.0,Adventure|Drama|Family|Fantasy,370.0,106072,fire|jungle|remake|tiger|wolf,English,UK,175000000.0,7.8
82,Maleficent,2014.0,Color,PG,97.0,Robert Stromberg,171.0,Angelina Jolie Pitt,11000.0,Sharlto Copley,...,846.0,241407328.0,Action|Adventure|Family|Fantasy|Romance,401.0,252257,curse|dark fantasy|fairy|king|kingdom,English,USA,180000000.0,7.0
84,The Lovers,2015.0,Color,R,109.0,Roland Joffé,596.0,Tamsin Egerton,622.0,Alice Englert,...,283.0,NaN,Action|Adventure|Romance|Sci-Fi,10.0,2138,1770s|british india|great barrier reef|india|ring,English,Belgium,NaN,4.5
87,Shrek Forever After,2010.0,Color,PG,93.0,Mike Mitchell,31.0,Jon Hamm,4000.0,Kathy Griffin,...,213.0,238371987.0,Adventure|Animation|Comedy|Family|Fantasy,226.0,138661,alternate world|fairy tale parody|female warri...,English,USA,165000000.0,6.4
88,Tomorrowland,2015.0,Color,PG,130.0,Brad Bird,663.0,Judy Greer,2000.0,Chris Bauer,...,604.0,93417865.0,Action|Adventure|Family|Mystery|Sci-Fi,443.0,128306,boy genius|futuristic city|inventor|teenage gi...,English,USA,190000000.0,6.5
89,Big Hero 6,2014.0,Color,PG,102.0,Don Hall,38.0,Damon Wayans Jr.,756.0,Daniel Henney,...,562.0,222487711.0,Action|Adventure|Animation|Comedy|Drama|Family...,384.0,279093,high tech|martial arts|masked man|robot|superhero,English,USA,165000000.0,7.9
90,Wreck-It Ralph,2012.0,Color,PG,101.0,Rich Moore,66.0,Jack McBrayer,975.0,Sarah Silverman,...,833.0,189412677.0,Adventure|Animation|Comedy|Family|Sci-Fi,377.0,272534,arcade|candy|glitch|king|medal,English,USA,165000000.0,7.8
93,How to Train Your Dragon,2010.0,Color,PG,98.0,Dean DeBlois,255.0,Gerard Butler,18000.0,America Ferrera,...,759.0,217387997.0,Adventure|Animation|Family|Fantasy,288.0,485430,dragon|island|training|viking|village,English,USA,165000000.0,8.2
94,Terminator 3: Rise of the Machines,2003.0,Color,R,109.0,Jonathan Mostow,84.0,Nick Stahl,648.0,M.C. Gainey,...,191.0,150350192.0,Action|Sci-Fi,280.0,305340,drifter|exploding truck|future|machine|skynet,English,USA,200000000.0,6.4
104,The Sorcerer's Apprentice,2010.0,Color,PG,109.0,Jon Turteltaub,226.0,Nicolas Cage,12000.0,Omar Benson Miller,...,370.0,63143812.0,Action|Adventure|Family|Fantasy,235.0,124185,chosen one|enchanted object|love|spell|training,English,USA,150000000.0,6.1
106,Alice Through the Looking Glass,2016.0,Color,PG,113.0,James Bobin,33.0,Johnny Depp,40000.0,Alan Rickman,...,11000.0,76846624.0,Adventure|Family|Fantasy,218.0,21352,clock|dark fantasy|mad hatter|queen|sequel,English,USA,170000000.0,6.4
107,Shrek the Third,2007.0,Color,PG,93.0,Chris Miller,50.0,Justin Timberlake,3000.0,Eric Idle,...,692.0,320706665.0,Adventure|Animation|Comedy|Family|Fantasy,227.0,211971,disney spoof|fairy tale|prince|princess|tough guy,English,USA,160000000.0,6.1
110,The Chronicles of Narnia: The Voyage of the Da...,2010.0,Color,PG,113.0,Michael Apted,150.0,Bruce Spence,531.0,Shane Rangi,...,59.0,104383624.0,Adventure|Family|Fantasy,228.0,106446,dragon|king|mouse|quest|warrior,English,USA,155000000.0,6.3
113,Alexander,2004.0,Color,R,206.0,Oliver Stone,0.0,Anthony Hopkins,12000.0,Angelina Jolie Pitt,...,591.0,34293771.0,Action|Adventure|Biography|Drama|History|Roman...,248.0,138863,ancient greece|conquest|greek|greek myth|king,English,Germany,155000000.0,5.5
118,Charlie and the Chocolate Factory,2005.0,Color,PG,115.0,Tim Burton,13000.0,Johnny Depp,40000.0,Christopher Lee,...,588.0,206456431.0,Adventure|Comedy|Family|Fantasy,276.0,320284,chocolate|diminution|miniaturization|physical ...,English,USA,150000000.0,6.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4831,The Gallows,2015.0,Color,R,81.0,Travis Cluff,3.0,Pfeifer Brown,220.0,Cassidy Gifford,...,7.0,22757819.0,Horror|Thriller,159.0,13521,breaking and entering|gallows|hanging|high sch...,English,USA,100000.0,4.2
4834,Hollywood Shuffle,1987.0,Color,R,81.0,Robert Townsend,467.0,Robert Townsend,467.0,Keenen Ivory Wayans,...,287.0,5228617.0,Comedy,21.0,2770,actor|african american|dream|two word title|wr...,English,USA,100000.0,7.0
4836,Penitentiary,1979.0,Color,R,99.0,Jamaa Fanaka,9.0,Leon Isaac Kennedy,116.0,Chuck Mitchell,...,10.0,NaN,Crime|Drama|Sport,23.0,509,blaxploitation|boxing|convict|drifter|false ac...,English,USA,100000.0,5.8
4837,The Lost Skeleton of Cadavra,2001.0,Black and White,PG,90.0,Larry Blamire,56.0,Fay Masterson,126.0,Brian Howe,...,56.0,110536.0,Comedy|Horror|Sci-Fi,88.0,4117,alien|cave|husband wife relationship|monster|s...,English,USA,40000.0,7.0
4838,"Dude, Where's My Dog?!",2014.0,Color,PG,82.0,Stephen Langford,7.0,Kevin P. Farley,143.0,Gabriela Castillo,...,50.0,NaN,Family,2.0,73,NaN,English,USA,20000.0,3.2
4841,Closure,2007.0,Color,R,80.0,Dan Reed,3.0,Danny Dyer,798.0,Adam Rayner,...,140.0,NaN,Thriller,61.0,5747,countryside|night|party|rape|scar,English,UK,1800000.0,5.6
4847,Pi,1998.0,Black and White,R,84.0,Darren Aronofsky,0.0,Mark Margolis,1000.0,Clint Mansell,...,194.0,3216970.0,Drama|Mystery|Thriller,138.0,142619,mathematician|nature|numbers|pattern|using a m...,English,USA,60000.0,7.5
4848,"I Love You, Don't Touch Me!",1997.0,Color,R,86.0,Julie Davis,12.0,Jack McGee,238.0,Meredith Scott Lynn,...,117.0,33598.0,Comedy|Romance,5.0,405,female frontal nudity|female rear nudity|title...,English,USA,NaN,5.4
4849,20 Dates,1998.0,Color,R,87.0,Myles Berkowitz,0.0,Tia Carrere,1000.0,Tom Ardavany,...,153.0,536767.0,Biography|Comedy|Romance,32.0,1622,fake documentary|hidden camera|mockumentary|na...,English,USA,60000.0,5.3
4851,Super Size Me,2004.0,Color,PG,100.0,Morgan Spurlock,293.0,Chemeeka Walker,0.0,Amanda Kearsan,...,0.0,11529368.0,Comedy|Documentary|Drama,193.0,85028,experiment|fast food|food industry|meal|overea...,English,USA,65000.0,7.3
4852,The FP,2011.0,Color,R,82.0,Brandon Trost,32.0,Clifton Collins Jr.,968.0,Sean Whalen,...,128.0,40557.0,Comedy,66.0,1389,abbreviation in title|based on short film|comp...,English,USA,60000.0,5.6
4853,Happy Christmas,2014.0,Color,R,82.0,Joe Swanberg,217.0,Anna Kendrick,10000.0,Lena Dunham,...,442.0,30084.0,Comedy|Drama,65.0,5507,chicago illinois|drink|drinking|filmmaker|writer,English,USA,70000.0,5.6
4857,Absentia,2011.0,Color,R,87.0,Mike Flanagan,59.0,Justin Gordon,35.0,Courtney Bell,...,9.0,NaN,Drama|Horror|Mystery,125.0,13065,anticipate|dead in absentia|foetus|tunnel|unre...,English,USA,70000.0,5.8
4858,The Brothers McMullen,1995.0,Color,R,98.0,Edward Burns,0.0,Shari Albert,138.0,Michael McGlone,...,73.0,10246600.0,Comedy|Drama|Romance,36.0,6375,abusive father|critically acclaimed|loss of fa...,English,USA,25000.0,6.6
4860,Gabriela,1983.0,Color,R,99.0,Bruno Barreto,9.0,Marcello Mastroianni,866.0,Sonia Braga,...,3.0,NaN,Comedy|Drama|Romance,1.0,712,based on novel|brazil|female underarm hair|sex...,Portuguese,Brazil,NaN,6.4
4869,This Is Martin Bonner,2013.0,Color,R,83.0,Chad Hartigan,3.0,Jan Haley,695.0,Paul Eenhoorn,...,69.0,NaN,Drama,34.0,733,estranged daughter|friendship|nevada|prisoner|...,English,USA,42000.0,6.6
4872,Smiling Fish & Goat on Fire,1999.0,Color,R,90.0,Kevin Jordan,4.0,Derick Martini,20000.0,Christa Miller,...,113.0,277233.0,Comedy|Romance,21.0,2631,accountant|actor|animal in title|mail carrier|...,English,USA,40000.0,7.6
4875,The Last Waltz,1978.0,Color,PG,117.0,Martin Scorsese,17000.0,Ringo Starr,725.0,Levon Helm,...,476.0,321952.0,Documentary|Music,71.0,12611,band|final concert|guitar|interview|thanksgiving,English,USA,NaN,8.2
4878,The Legend of God's Gun,2007.0,Color,R,78.0,Mike Bruce,6.0,Joseph Campanella,32.0,Kirpatrick Thomas,...,17.0,243768.0,Western,3.0,143,NaN,English,USA,30000.0,4.1
4879,Mutual Appreciation,2005.0,Black and White,R,109.0,Andrew Bujalski,26.0,Andrew Bujalski,26.0,Kate Dollenmayer,...,3.0,NaN,Comedy,52.0,1578,friendship|guitarist|mumblecore|musician|new york,English,USA,NaN,6.9
4881,Down Terrace,2009.0,Color,R,93.0,Ben Wheatley,214.0,Michael Smiley,177.0,Tony Way,...,59.0,9609.0,Comedy|Crime|Drama,53.0,2646,black comedy,English,UK,NaN,6.5
4882,Clerks,1994.0,Black and White,R,102.0,Kevin Smith,0.0,Jason Mewes,898.0,Brian O'Halloran,...,216.0,3151130.0,Comedy,136.0,181749,clerk|friend|hockey|video|video store,English,USA,230000.0,7.8
4885,In the Company of Men,1997.0,Color,R,97.0,Neil LaBute,119.0,Stacy Edwards,136.0,Matt Malloy,...,7.0,2856622.0,Comedy|Drama,80.0,11550,business trip|love|misogynist|office|secretary,English,Canada,25000.0,7.3
4887,Rampage,2009.0,Color,R,80.0,Uwe Boll,892.0,Matt Frewer,986.0,Katharine Isabelle,...,492.0,NaN,Action|Crime|Thriller,58.0,15091,death|first part|killing spree|massacre|murder,English,Canada,NaN,6.3
4888,Slacker,1991.0,Black and White,R,100.0,Richard Linklater,0.0,Tommy Pallotta,5.0,Richard Linklater,...,0.0,1227508.0,Comedy|Drama,61.0,15103,austin texas|moon|pap smear|texas|twenty somet...,English,USA,23000.0,7.1
4892,Exeter,2015.0,Color,R,91.0,Marcus Nispel,158.0,Ashley Tramonte,630.0,Brittany Curran,...,265.0,NaN,Horror|Mystery|Thriller,43.0,3836,asylum|demon|party|secret|teenager,English,USA,NaN,4.6
4894,The Puffy Chair,2005.0,Color,R,85.0,Jay Duplass,157.0,Mark Duplass,830.0,Katie Aselton,...,10.0,192467.0,Comedy|Drama|Romance,51.0,4067,birthday|gift|motel|new york city|upholsterer,English,USA,15000.0,6.6
4899,Clean,2004.0,Color,R,110.0,Olivier Assayas,107.0,Maggie Cheung,576.0,Béatrice Dalle,...,45.0,136007.0,Drama|Music|Romance,81.0,3924,jail|junkie|money|motel|singer,French,France,4500.0,6.9
4908,El Mariachi,1992.0,Color,R,81.0,Robert Rodriguez,0.0,Carlos Gallardo,121.0,Peter Marquardt,...,6.0,2040920.0,Action|Crime|Drama|Romance|Thriller,56.0,52055,assassin|death|guitar|gun|mariachi,Spanish,USA,7000.0,6.9
4915,My Date with Drew,2004.0,Color,PG,90.0,Jon Gunn,16.0,John August,86.0,Brian Herzlinger,...,16.0,85222.0,Documentary,43.0,4285,actress name in title|crush|date|four word tit...,English,USA,1100.0,6.6

### Problem 3
<span  style="color:green; font-size:16px">Select movies that are either rated PG-13 or were made after 2010.</span>

In [25]:
# your code here
filt1 = movie['content_rating'] == 'PG-13'
filt2 = movie['year'] > 2010
filt = filt1 | filt2

movie[filt].head()

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,PG-13,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1

### Problem 4
<span  style="color:green; font-size:16px">Find all the movies that have at least one of the three actors with more than 10,000 Facebook likes.</span>

In [26]:
# your code here
filt1 = movie['actor1_fb'] > 10000
filt2 = movie['actor2_fb'] > 10000
filt3 = movie['actor3_fb'] > 10000

filt = filt1 | filt2 | filt3

movie[filt].head()

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
6,Spider-Man 3,2007.0,Color,PG-13,156.0,Sam Raimi,0.0,J.K. Simmons,24000.0,James Franco,...,4000.0,336530303.0,Action|Adventure|Romance,392.0,383056,sandman|spider man|symbiote|venom|villain,English,USA,258000000.0,6.2
8,Avengers: Age of Ultron,2015.0,Color,PG-13,141.0,Joss Whedon,0.0,Chris Hemsworth,26000.0,Robert Downey Jr.,...,19000.0,458991599.0,Action|Adventure|Sci-Fi,635.0,462669,artificial intelligence|based on comic book|ca...,English,USA,250000000.0,7.5

### Problem 5
<span  style="color:green; font-size:16px">Reverse the condition from problem 3. In words, what have you selected.</span>

In [33]:
# your code here
filt1 = movie['content_rating'] == 'PG-13'
filt2 = movie['year'] > 2010
filt = filt1 | filt2

movie[~filt].head()

Empty DataFrame
Columns: [title, year, color, content_rating, duration, director_name, director_fb, actor1, actor1_fb, actor2, actor2_fb, actor3, actor3_fb, gross, genres, num_reviews, num_voted_users, plot_keywords, language, country, budget, imdb_score]
Index: []

[0 rows x 22 columns]

In [38]:
filt1 = movie['content_rating'] == 'PG-13'
filt2 = movie['year'] > 2010
filt = filt1 | filt2

movie[filt].shape

(4916, 22)

In [36]:
movie
movie.shape

(4916, 22)

In [39]:
movie

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,PG-13,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1
5,John Carter,2012.0,Color,PG-13,132.0,Andrew Stanton,475.0,Daryl Sabara,640.0,Samantha Morton,...,530.0,73058679.0,Action|Adventure|Sci-Fi,462.0,212204,alien|american civil war|male nipple|mars|prin...,English,USA,263700000.0,6.6
6,Spider-Man 3,2007.0,Color,PG-13,156.0,Sam Raimi,0.0,J.K. Simmons,24000.0,James Franco,...,4000.0,336530303.0,Action|Adventure|Romance,392.0,383056,sandman|spider man|symbiote|venom|villain,English,USA,258000000.0,6.2
7,Tangled,2010.0,Color,PG-13,100.0,Nathan Greno,15.0,Brad Garrett,799.0,Donna Murphy,...,284.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,324.0,294810,17th century|based on fairy tale|disney|flower...,English,USA,260000000.0,7.8
8,Avengers: Age of Ultron,2015.0,Color,PG-13,141.0,Joss Whedon,0.0,Chris Hemsworth,26000.0,Robert Downey Jr.,...,19000.0,458991599.0,Action|Adventure|Sci-Fi,635.0,462669,artificial intelligence|based on comic book|ca...,English,USA,250000000.0,7.5
9,Harry Potter and the Half-Blood Prince,2009.0,Color,PG-13,153.0,David Yates,282.0,Alan Rickman,25000.0,Daniel Radcliffe,...,10000.0,301956980.0,Adventure|Family|Fantasy|Mystery,375.0,321795,blood|book|love|potion|professor,English,UK,250000000.0,7.5
10,Batman v Superman: Dawn of Justice,2016.0,Color,PG-13,183.0,Zack Snyder,0.0,Henry Cavill,15000.0,Lauren Cohan,...,2000.0,330249062.0,Action|Adventure|Sci-Fi,673.0,371639,based on comic book|batman|sequel to a reboot|...,English,USA,250000000.0,6.9
11,Superman Returns,2006.0,Color,PG-13,169.0,Bryan Singer,0.0,Kevin Spacey,18000.0,Marlon Brando,...,903.0,200069408.0,Action|Adventure|Sci-Fi,434.0,240396,crystal|epic|lex luthor|lois lane|return to earth,English,USA,209000000.0,6.1
12,Quantum of Solace,2008.0,Color,PG-13,106.0,Marc Forster,395.0,Giancarlo Giannini,451.0,Mathieu Amalric,...,393.0,168368427.0,Action|Adventure,403.0,330784,action hero|attempted rape|bond girl|official ...,English,UK,200000000.0,6.7
13,Pirates of the Caribbean: Dead Man's Chest,2006.0,Color,PG-13,151.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,423032628.0,Action|Adventure|Fantasy,313.0,522040,box office hit|giant squid|heart|liar's dice|m...,English,USA,225000000.0,7.3
14,The Lone Ranger,2013.0,Color,PG-13,150.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Ruth Wilson,...,1000.0,89289910.0,Action|Adventure|Western,450.0,181792,horse|outlaw|texas|texas ranger|train,English,USA,215000000.0,6.5
15,Man of Steel,2013.0,Color,PG-13,143.0,Zack Snyder,0.0,Henry Cavill,15000.0,Christopher Meloni,...,748.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,733.0,548573,based on comic book|british actor playing amer...,English,USA,225000000.0,7.2
16,The Chronicles of Narnia: Prince Caspian,2008.0,Color,PG-13,150.0,Andrew Adamson,80.0,Peter Dinklage,22000.0,Pierfrancesco Favino,...,201.0,141614023.0,Action|Adventure|Family|Fantasy,258.0,149922,brother brother relationship|brother sister re...,English,USA,225000000.0,6.6
17,The Avengers,2012.0,Color,PG-13,173.0,Joss Whedon,0.0,Chris Hemsworth,26000.0,Robert Downey Jr.,...,19000.0,623279547.0,Action|Adventure|Sci-Fi,703.0,995415,alien invasion|assassin|battle|iron man|soldier,English,USA,220000000.0,8.1
18,Pirates of the Caribbean: On Stranger Tides,2011.0,Color,PG-13,136.0,Rob Marshall,252.0,Johnny Depp,40000.0,Sam Claflin,...,1000.0,241063875.0,Action|Adventure|Fantasy,448.0,370704,blackbeard|captain|pirate|revenge|soldier,English,USA,250000000.0,6.7
19,Men in Black 3,2012.0,Color,PG-13,106.0,Barry Sonnenfeld,188.0,Will Smith,10000.0,Michael Stuhlbarg,...,718.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,451.0,268154,alien|criminal|m.i.b.|maximum security prison|...,English,USA,225000000.0,6.8
20,The Hobbit: The Battle of the Five Armies,2014.0,Color,PG-13,164.0,Peter Jackson,0.0,Aidan Turner,5000.0,Adam Brown,...,773.0,255108370.0,Adventure|Fantasy,422.0,354228,army|elf|hobbit|middle earth|orc,English,New Zealand,250000000.0,7.5
21,The Amazing Spider-Man,2012.0,Color,PG-13,153.0,Marc Webb,464.0,Emma Stone,15000.0,Andrew Garfield,...,963.0,262030663.0,Action|Adventure|Fantasy,599.0,451803,lizard|outcast|spider|spider man|teenager,English,USA,230000000.0,7.0
22,Robin Hood,2010.0,Color,PG-13,156.0,Ridley Scott,0.0,Mark Addy,891.0,William Hurt,...,738.0,105219735.0,Action|Adventure|Drama|History,343.0,211765,1190s|archer|england|king of england|robin hood,English,USA,200000000.0,6.7
23,The Hobbit: The Desolation of Smaug,2013.0,Color,PG-13,186.0,Peter Jackson,0.0,Aidan Turner,5000.0,Adam Brown,...,773.0,258355354.0,Adventure|Fantasy,509.0,483540,dwarf|elf|lake town|mountain|sword and sorcery,English,USA,225000000.0,7.9
24,The Golden Compass,2007.0,Color,PG-13,113.0,Chris Weitz,129.0,Christopher Lee,16000.0,Eva Green,...,1000.0,70083519.0,Adventure|Family|Fantasy,251.0,149019,children|epic|friend|girl|quest,English,USA,180000000.0,6.1
25,King Kong,2005.0,Color,PG-13,201.0,Peter Jackson,0.0,Naomi Watts,6000.0,Thomas Kretschmann,...,84.0,218051260.0,Action|Adventure|Drama|Romance,446.0,316018,animal name in title|ape abducts a woman|goril...,English,New Zealand,207000000.0,7.2
26,Titanic,1997.0,Color,PG-13,194.0,James Cameron,0.0,Leonardo DiCaprio,29000.0,Kate Winslet,...,794.0,658672302.0,Drama|Romance,315.0,793059,artist|love|ship|titanic|wet,English,USA,200000000.0,7.7
27,Captain America: Civil War,2016.0,Color,PG-13,147.0,Anthony Russo,94.0,Robert Downey Jr.,21000.0,Scarlett Johansson,...,11000.0,407197282.0,Action|Adventure|Sci-Fi,516.0,272670,based on comic book|knife|marvel cinematic uni...,English,USA,250000000.0,8.2
28,Battleship,2012.0,Color,PG-13,131.0,Peter Berg,532.0,Liam Neeson,14000.0,Alexander Skarsgård,...,627.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,377.0,202382,box office flop|hawaii|naval|oahu hawaii|ship,English,USA,209000000.0,5.9
29,Jurassic World,2015.0,Color,PG-13,124.0,Colin Trevorrow,365.0,Bryce Dallas Howard,3000.0,Judy Greer,...,1000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,644.0,418214,dinosaur|disaster film|experiment gone wrong|j...,English,USA,150000000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,Manito,2002.0,Color,PG-13,79.0,Eric Eason,3.0,Franky G,93.0,Panchito Gómez,...,42.0,NaN,Drama|Family,28.0,493,ex convict|graduation|manhattan new york city|...,English,USA,24000.0,7.0
4887,Rampage,2009.0,Color,PG-13,80.0,Uwe Boll,892.0,Matt Frewer,986.0,Katharine Isabelle,...,492.0,NaN,Action|Crime|Thriller,58.0,15091,death|first part|killing spree|massacre|murder,English,Canada,NaN,6.3
4888,Slacker,1991.0,Black and White,PG-13,100.0,Richard Linklater,0.0,Tommy Pallotta,5.0,Richard Linklater,...,0.0,1227508.0,Comedy|Drama,61.0,15103,austin texas|moon|pap smear|texas|twenty somet...,English,USA,23000.0,7.1
4889,Dutch Kills,2015.0,Color,PG-13,90.0,Joseph Mazzella,0.0,Tjasa Ferme,313.0,Mikaal Bates,...,9.0,NaN,Crime|Drama|Thriller,NaN,57,NaN,English,USA,25000.0,4.8
4890,Dry Spell,2013.0,Color,PG-13,90.0,Travis Legge,138.0,Kristen Seavey,370.0,Suzi Lorraine,...,138.0,NaN,Comedy|Romance,1.0,114,anti romantic comedy|dating|divorce|sex comedy...,English,USA,22000.0,3.3
4891,Flywheel,2003.0,Color,PG-13,120.0,Alex Kendrick,589.0,Shannen Fields,51.0,Lisa Arnold,...,4.0,NaN,Drama,5.0,2986,baby|car salesman|christian film|pregnancy|use...,English,USA,20000.0,6.9
4892,Exeter,2015.0,Color,PG-13,91.0,Marcus Nispel,158.0,Ashley Tramonte,630.0,Brittany Curran,...,265.0,NaN,Horror|Mystery|Thriller,43.0,3836,asylum|demon|party|secret|teenager,English,USA,NaN,4.6
4893,The Ridges,2011.0,NaN,PG-13,143.0,Brandon Landers,8.0,Robbie Barnes,720.0,Alana Kaniewski,...,8.0,NaN,Drama|Horror|Thriller,NaN,125,avatar|college|death|tron|university,English,USA,17350.0,3.0
4894,The Puffy Chair,2005.0,Color,PG-13,85.0,Jay Duplass,157.0,Mark Duplass,830.0,Katie Aselton,...,10.0,192467.0,Comedy|Drama|Romance,51.0,4067,birthday|gift|motel|new york city|upholsterer,English,USA,15000.0,6.6
4895,Stories of Our Lives,2014.0,Black and White,PG-13,60.0,Jim Chuchu,0.0,Paul Ogola,147.0,Olwenya Maina,...,4.0,NaN,Drama,6.0,70,NaN,Swahili,Kenya,15000.0,7.4
4896,Breaking Upwards,2009.0,Color,PG-13,88.0,Daryl Wein,38.0,Zoe Lister-Jones,331.0,Heather Burns,...,211.0,76382.0,Romance,22.0,1194,NaN,English,USA,15000.0,6.2
4897,All Superheroes Must Die,2011.0,Color,PG-13,78.0,Jason Trost,91.0,Sean Whalen,407.0,Jason Trost,...,86.0,NaN,Sci-Fi|Thriller,42.0,1771,arch villain|game of death|kidnapping|superhero,English,USA,20000.0,4.0
4898,Pink Flamingos,1972.0,Color,PG-13,108.0,John Waters,0.0,Divine,462.0,Mink Stole,...,105.0,180483.0,Comedy|Crime|Horror,73.0,16792,absurd humor|egg|gross out humor|lesbian|sex,English,USA,10000.0,6.1
4899,Clean,2004.0,Color,PG-13,110.0,Olivier Assayas,107.0,Maggie Cheung,576.0,Béatrice Dalle,...,45.0,136007.0,Drama|Music|Romance,81.0,3924,jail|junkie|money|motel|singer,French,France,4500.0,6.9
4900,The Circle,2000.0,Color,PG-13,90.0,Jafar Panahi,397.0,Fereshteh Sadre Orafaiy,5.0,Nargess Mamizadeh,...,0.0,673780.0,Drama,64.0,4555,abortion|bus|hospital|prison|prostitution,Persian,Iran,10000.0,7.5
4901,Tin Can Man,2007.0,Black and White,PG-13,83.0,Ivan Kavanagh,18.0,Patrick O'Donnell,10.0,Michael Parle,...,0.0,NaN,Horror,12.0,57,NaN,English,Ireland,10000.0,6.7
4902,The Cure,1997.0,Color,PG-13,111.0,Kiyoshi Kurosawa,62.0,Kôji Yakusho,89.0,Anna Nakagawa,...,6.0,94596.0,Crime|Horror|Mystery|Thriller,78.0,6318,breasts|interrogation|investigation|murder|wat...,Japanese,Japan,1000000.0,7.4
4903,On the Downlow,2004.0,Color,PG-13,84.0,Tadeo Garcia,5.0,Tatiana Suarez-Pico,21.0,Michael Cortez,...,12.0,NaN,Drama,NaN,156,gang initiation|gunplay|hazing|latino|shakespe...,English,USA,NaN,6.1
4904,Sanctuary; Quite a Conundrum,2012.0,Color,PG-13,82.0,Thomas L. Phillips,120.0,Julianna Pitt,785.0,Joe Coffey,...,84.0,NaN,Comedy|Horror|Thriller,13.0,133,nudity|party|pirate|swimsuit|three word title,English,USA,200000.0,5.4
4905,Bang,1995.0,Color,PG-13,98.0,Ash Baron-Cohen,3.0,Peter Greene,789.0,Stanley B. Herman,...,152.0,NaN,Crime|Drama,10.0,438,corruption|homeless|homeless man|motorcycle|ur...,English,USA,NaN,6.4
4906,Primer,2004.0,Color,PG-13,77.0,Shane Carruth,291.0,Shane Carruth,291.0,David Sullivan,...,8.0,424760.0,Drama|Sci-Fi|Thriller,143.0,72639,changing the future|independent film|invention...,English,USA,7000.0,7.0
4907,Cavite,2005.0,Color,PG-13,80.0,Neill Dela Llana,0.0,Ian Gamazon,0.0,Edgar Tancangco,...,0.0,70071.0,Thriller,35.0,589,jihad|mindanao|philippines|security guard|squa...,English,Philippines,7000.0,6.3
4908,El Mariachi,1992.0,Color,PG-13,81.0,Robert Rodriguez,0.0,Carlos Gallardo,121.0,Peter Marquardt,...,6.0,2040920.0,Action|Crime|Drama|Romance|Thriller,56.0,52055,assassin|death|guitar|gun|mariachi,Spanish,USA,7000.0,6.9
4909,The Mongol King,2005.0,Color,PG-13,84.0,Anthony Vallone,2.0,Richard Jewell,45.0,John Considine,...,2.0,NaN,Crime|Drama,NaN,36,jewell|mongol|nostradamus|stepnicka|vallone,English,USA,3250.0,7.8
4910,Newlyweds,2011.0,Color,PG-13,95.0,Edward Burns,0.0,Kerry Bishé,296.0,Caitlin FitzGerald,...,133.0,4584.0,Comedy|Drama,14.0,1338,written and directed by cast member,English,USA,9000.0,6.4
4911,Signed Sealed Delivered,2013.0,Color,PG-13,87.0,Scott Smith,2.0,Eric Mabius,637.0,Daphne Zuniga,...,318.0,NaN,Comedy|Drama,1.0,629,fraud|postal worker|prison|theft|trial,English,Canada,NaN,7.7
4912,The Following,NaN,Color,PG-13,43.0,NaN,NaN,Natalie Zea,841.0,Valorie Curry,...,319.0,NaN,Crime|Drama|Mystery|Thriller,43.0,73839,cult|fbi|hideout|prison escape|serial killer,English,USA,NaN,7.5
4913,A Plague So Pleasant,2013.0,Color,PG-13,76.0,Benjamin Roberds,0.0,Eva Boehnke,0.0,Maxwell Moody,...,0.0,NaN,Drama|Horror|Thriller,13.0,38,NaN,English,USA,1400.0,6.3
4914,Shanghai Calling,2012.0,Color,PG-13,100.0,Daniel Hsia,0.0,Alan Ruck,946.0,Daniel Henney,...,489.0,10443.0,Comedy|Drama|Romance,14.0,1255,NaN,English,USA,NaN,6.3
4915,My Date with Drew,2004.0,Color,PG-13,90.0,Jon Gunn,16.0,John August,86.0,Brian Herzlinger,...,16.0,85222.0,Documentary,43.0,4285,actress name in title|crush|date|four word tit...,English,USA,1100.0,6.6